# Generated by Django 3.2.4 on 2023-11-06 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('captain_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_id', to=settings.AUTH_USER_MODEL)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to=settings.AUTH_USER_MODEL)),
                ('sport_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sporttype')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sporttype')),
                ('tournament_system_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tournamentsystem')),
                ('tournament_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tournamenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TeamsTournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TeamParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=64)),
                ('photo_path', models.CharField(max_length=64)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('result', models.CharField(max_length=16)),
                ('team_away_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_away_id', to='api.team')),
                ('team_home_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_home_id', to='api.team')),
            ],
        ),
    ]
