# Generated by Django 3.2.4 on 2023-11-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentSystem',
            new_name='TournamentScheduleSystem',
        ),
    ]
