# Generated by Django 3.2.4 on 2023-11-15 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20231109_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_type_id', to='api.sporttype'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sport_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_type', to='api.sporttype'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_system_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_system', to='api.tournamentschedulesystem'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_type', to='api.tournamenttype'),
        ),
    ]
