# Generated by Django 3.2.4 on 2023-11-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231115_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='teams', through='api.TeamsTournaments', to='api.Team'),
        ),
    ]
