export const GET_TOURNAMENTS_REQUEST: 'GET_TOURNAMENTS_REQUEST' = 'GET_TOURNAMENTS_REQUEST';
export const GET_TOURNAMENTS_SUCCESS: 'GET_TOURNAMENTS_SUCCESS' = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAILED: 'GET_TOURNAMENTS_FAILED' = 'GET_TOURNAMENTS_FAILED';

export const GET_TOURNAMENT_REQUEST: 'GET_TOURNAMENT_REQUEST' = 'GET_TOURNAMENT_REQUEST';
export const GET_TOURNAMENT_SUCCESS: 'GET_TOURNAMENT_SUCCESS' = 'GET_TOURNAMENT_SUCCESS';
export const GET_TOURNAMENT_FAILED: 'GET_TOURNAMENT_FAILED' = 'GET_TOURNAMENT_FAILED';

export const CLEAR_TOURNAMENT: 'CLEAR_TOURNAMENT' = 'CLEAR_TOURNAMENT';
export const CREATE_TOURNAMENT_GRID: 'CREATE_TOURNAMENT_GRID' = 'CREATE_TOURNAMENT_GRID';

export const SAVE_TOURNAMENT_GRID_REQUEST: 'SAVE_TOURNAMENT_GRID_REQUEST' = 'SAVE_TOURNAMENT_GRID_REQUEST';
export const SAVE_TOURNAMENT_GRID_SUCCESS: 'SAVE_TOURNAMENT_GRID_SUCCESS' = 'SAVE_TOURNAMENT_GRID_SUCCESS';
export const SAVE_TOURNAMENT_GRID_FAILED: 'SAVE_TOURNAMENT_GRID_FAILED' = 'SAVE_TOURNAMENT_GRID_FAILED';