export const GET_TOURNAMENTS_REQUEST: 'GET_TOURNAMENTS_REQUEST' = 'GET_TOURNAMENTS_REQUEST';
export const GET_TOURNAMENTS_SUCCESS: 'GET_TOURNAMENTS_SUCCESS' = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAILED: 'GET_TOURNAMENTS_FAILED' = 'GET_TOURNAMENTS_FAILED';

export const GET_TOURNAMENT_REQUEST: 'GET_TOURNAMENT_REQUEST' = 'GET_TOURNAMENT_REQUEST';
export const GET_TOURNAMENT_SUCCESS: 'GET_TOURNAMENT_SUCCESS' = 'GET_TOURNAMENT_SUCCESS';
export const GET_TOURNAMENT_FAILED: 'GET_TOURNAMENT_FAILED' = 'GET_TOURNAMENT_FAILED';

export const CLEAR_TOURNAMENT: 'CLEAR_TOURNAMENT' = 'CLEAR_TOURNAMENT';
