# Generated by Django 3.2.4 on 2023-12-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_team_ban_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='count_teams',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество команд'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/tournaments/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
