export const GET_TEAMS_REQUEST: 'GET_TEAMS_REQUEST' = 'GET_TEAMS_REQUEST';
export const GET_TEAMS_SUCCESS: 'GET_TEAMS_SUCCESS' = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAILED: 'GET_TEAMS_FAILED' = 'GET_TEAMS_FAILED';

export const GET_TEAM_REQUEST: 'GET_TEAM_REQUEST' = 'GET_TEAM_REQUEST';
export const GET_TEAM_SUCCESS: 'GET_TEAM_SUCCESS' = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAILED: 'GET_TEAM_FAILED' = 'GET_TEAM_FAILED';

export const CLEAR_TEAM: 'CLEAR_TEAM' = 'CLEAR_TEAM';
