export const GET_USER: 'GET_USER' = 'GET_USER'
export const SET_USER: 'SET_USER' = 'SET_USER'

export const USER_PROFILE_REQUEST: 'USER_PROFILE_REQUEST' = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS: 'USER_PROFILE_SUCCESS' = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED: 'USER_PROFILE_FAILED' = 'USER_PROFILE_FAILED';

export const SET_USER_FAILED: 'SET_USER_FAILED' = 'SET_USER_FAILED'
export const SET_AUTH_CHECKED: 'SET_AUTH_CHECKED' = 'SET_AUTH_CHECKED'

export const REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST' = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS' = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED: 'REGISTER_USER_FAILED' = 'REGISTER_USER_FAILED';

export const LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST' = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS' = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED: 'LOGIN_USER_FAILED' = 'LOGIN_USER_FAILED';

export const LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST' = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS' = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED: 'LOGOUT_USER_FAILED' = 'LOGOUT_USER_FAILED';